#
# Makefile
#
# Erzeugt die Beispiel-Programme zur Systemprogrammierung Teil 5
# Beispiel: make io
#
# Autor: H.Drachenfels
# Erstellt am: 15.4.2021
#

CXX=g++
CXXFLAGS = -g -Wall -Wextra -std=c++11 -pedantic

